[project]
name = "project-360"
version = "2.5.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.31.0",
    "aiohttp>=3.14.4",
    "aiomysql>=0.3.2",
    "cachetools>=7.2.1",
    "cachetools-async>=0.0.5",
    "cryptography>=50.0.2",
    "curl-cffi>=0.16.3",
    "drissionpage>=4.1.1.4",
    "nodriver>=0.50.6",
    "numpy>=2.5.3",
    "openai>=3.27.0",
    "petrovich>=2.0.1",
    "python-dateutil>=2.9.0.post0",
    "redis>=8.1.0",
    "wasmtime>=49.0.0",
]
